q2: l1q2.py
	python3 l1q2.py
q3: l1q3.py
	python3 l1q3.py
q4: l1q4.py
	python3 l1q4.py
q5: l1q5.py
	python3 l1q5.py

l2q1: l2q1.py
	python3 l2q1.py
l2q2: l2q2.py
	python3 l2q2.py
l2q3: l2q3.py
	python3 l2q3.py
l2q4: l2q4.py
	python3 l2q4.py

clean:
	rm imagens/requantizadas/*